#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef LONGRIVERBASE_SWIFT_H
#define LONGRIVERBASE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LongriverBase",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class UIScene;
@class UISceneSession;
@class UISceneConnectionOptions;
@class UIApplication;
@class NSURL;
@class UIOpenURLContext;
@class NSString;

SWIFT_CLASS("_TtC13LongriverBase9DOMAdjust")
@interface DOMAdjust : NSObject
- (void)scene:(UIScene * _Nonnull)scene willConnectTo:(UISceneSession * _Nonnull)session options:(UISceneConnectionOptions * _Nonnull)connectionOptions SWIFT_AVAILABILITY(ios,introduced=13.0);
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
+ (DOMAdjust * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)scene:(UIScene * _Nonnull)scene openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase11FJConstants")
@interface FJConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_AD_LOAD;)
+ (NSString * _Nonnull)EVENT_TAG_AD_LOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_AD_LOAD_FAIL;)
+ (NSString * _Nonnull)EVENT_TAG_AD_LOAD_FAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_AD_SHOW;)
+ (NSString * _Nonnull)EVENT_TAG_AD_SHOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_AD_CLICK;)
+ (NSString * _Nonnull)EVENT_TAG_AD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_ADD_TO_CART;)
+ (NSString * _Nonnull)EVENT_TAG_ADD_TO_CART SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_INIT_CHECKOUT;)
+ (NSString * _Nonnull)EVENT_TAG_INIT_CHECKOUT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PURCHASE;)
+ (NSString * _Nonnull)EVENT_TAG_PURCHASE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_SUBSCRIPTION;)
+ (NSString * _Nonnull)EVENT_TAG_SUBSCRIPTION SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase18KAdvertisingModule")
@interface KAdvertisingModule : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEVICE;)
+ (NSString * _Nonnull)DEVICE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull FACEBOOK;)
+ (NSString * _Nonnull)FACEBOOK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull GAMECENTER;)
+ (NSString * _Nonnull)GAMECENTER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull APPLE;)
+ (NSString * _Nonnull)APPLE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull GOOGLE;)
+ (NSString * _Nonnull)GOOGLE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase10KLifecycle")
@interface KLifecycle : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase23LongriverAdCallbackInfo")
@interface LongriverAdCallbackInfo : NSObject
@property (nonatomic) double revenue;
@property (nonatomic, copy) NSString * _Nullable network;
@property (nonatomic, copy) NSString * _Nullable placementId;
@property (nonatomic, copy) NSString * _Nullable adsourceId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase25LongriverAppleCheckResult")
@interface LongriverAppleCheckResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LongriverAttrInfoBuilder;

SWIFT_CLASS("_TtC13LongriverBase17LongriverAttrInfo")
@interface LongriverAttrInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull trackerToken;
@property (nonatomic, copy) NSString * _Nonnull trackerName;
@property (nonatomic, copy) NSString * _Nullable attrid;
@property (nonatomic, copy) NSString * _Nullable network;
@property (nonatomic, copy) NSString * _Nullable campaign;
@property (nonatomic, copy) NSString * _Nullable adgroup;
@property (nonatomic, copy) NSString * _Nullable creative;
@property (nonatomic, copy) NSString * _Nullable fbInstallReferrer;
+ (LongriverAttrInfoBuilder * _Nonnull)Builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase24LongriverAttrInfoBuilder")
@interface LongriverAttrInfoBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13LongriverBase24LongriverAutoLoginResult")
@interface LongriverAutoLoginResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic) BOOL isNew;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase31LongriverBindTransferCodeResult")
@interface LongriverBindTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LongriverBridgeResultBuilder;

/// Result of Bridge
SWIFT_CLASS("_TtC13LongriverBase21LongriverBridgeResult")
@interface LongriverBridgeResult : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull Success;)
+ (LongriverBridgeResult * _Nonnull)Success SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull Found;)
+ (LongriverBridgeResult * _Nonnull)Found SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull Redirect;)
+ (LongriverBridgeResult * _Nonnull)Redirect SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull Failed;)
+ (LongriverBridgeResult * _Nonnull)Failed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull NotFound;)
+ (LongriverBridgeResult * _Nonnull)NotFound SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull NotSupport;)
+ (LongriverBridgeResult * _Nonnull)NotSupport SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull PreconditionFailed;)
+ (LongriverBridgeResult * _Nonnull)PreconditionFailed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull ErrorParameter;)
+ (LongriverBridgeResult * _Nonnull)ErrorParameter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverBridgeResult * _Nonnull ErrorInternal;)
+ (LongriverBridgeResult * _Nonnull)ErrorInternal SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (LongriverBridgeResultBuilder * _Nonnull)Builder SWIFT_WARN_UNUSED_RESULT;
- (LongriverBridgeResult * _Nonnull)withMsg:(NSString * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
- (LongriverBridgeResult * _Nonnull)withData:(id _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
+ (NSString * _Nonnull)toString:(id _Nullable)any SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isValid:(id _Nullable)any SWIFT_WARN_UNUSED_RESULT;
- (BOOL)equal:(LongriverBridgeResult * _Nonnull)result SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCode SWIFT_WARN_UNUSED_RESULT;
- (void)setCode:(NSInteger)code;
- (NSString * _Nonnull)getMsg SWIFT_WARN_UNUSED_RESULT;
- (void)setMsg:(NSString * _Nonnull)msg;
- (NSString * _Nullable)getData SWIFT_WARN_UNUSED_RESULT;
- (void)setData:(NSString * _Nonnull)data;
+ (BOOL)scan:(NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC13LongriverBase28LongriverBridgeResultBuilder")
@interface LongriverBridgeResultBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13LongriverBase25LongriverCheckLoginResult")
@interface LongriverCheckLoginResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase20LongriverCustomEvent")
@interface LongriverCustomEvent : NSObject
@property (nonatomic, copy) NSString * _Nullable eventTag;
@property (nonatomic, copy) NSString * _Nullable eventName;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable logs;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable partnerParameter;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable callbackParameter;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable revenue;
@property (nonatomic, copy) NSString * _Nullable callbackId;
@property (nonatomic, copy) NSString * _Nullable orderId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable purchaseToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase25LongriverFirebaseDelegate_")
@protocol LongriverFirebaseDelegate <NSObject>
- (void)onMessageReceived:(NSDictionary<NSString *, id> * _Nonnull)message;
- (void)onFCMTokenRefresh:(NSString * _Nonnull)token;
- (void)onRemoteConfigFetchCompletion:(BOOL)success :(NSString * _Nullable)error;
- (void)onRemoteConfigActivated;
- (void)onFirebaseInitialized:(BOOL)success :(NSString * _Nullable)error;
- (void)onRemoteConfigInitialized:(BOOL)success :(NSString * _Nullable)error;
- (void)onMessagingInitialized:(BOOL)success :(NSString * _Nullable)error;
@end


SWIFT_CLASS("_TtC13LongriverBase35LongriverGenerateTransferCodeResult")
@interface LongriverGenerateTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable transferCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase34LongriverGetBindTransferCodeResult")
@interface LongriverGetBindTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase18LongriverLoginInfo")
@interface LongriverLoginInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable platform;
@property (nonatomic) BOOL hasLinked;
@property (nonatomic, copy) NSString * _Nullable uniqeId;
@property (nonatomic, copy) NSString * _Nullable iconUrl;
@property (nonatomic, copy) NSString * _Nullable nickName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase20LongriverLoginParams")
@interface LongriverLoginParams : NSObject
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase20LongriverLoginResult")
@interface LongriverLoginResult : NSObject
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic, copy) NSString * _Nullable sessionToken;
@property (nonatomic) BOOL isNew;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase25LongriverLoginThirdResult")
@interface LongriverLoginThirdResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13LongriverBase23LongriverNativeAdBinder")
@interface LongriverNativeAdBinder : NSObject
- (nonnull instancetype)xibName:(NSString * _Nonnull)xibName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)titleLabelTag:(NSInteger)titleLabelTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)bodyLabelTag:(NSInteger)bodyLabelTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)iconImageViewTag:(NSInteger)iconImageViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)mediaContentViewTag:(NSInteger)mediaContentViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)starRatingContentViewTag:(NSInteger)starRatingContentViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)advertiserLabelTag:(NSInteger)advertiserLabelTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)optionsContentViewTag:(NSInteger)optionsContentViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)callToActionButtonTag:(NSInteger)callToActionButtonTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)storeViewTag:(NSInteger)storeViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)priceViewTag:(NSInteger)priceViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)advertiserViewTag:(NSInteger)advertiserViewTag SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase20LongriverOneTimeItem")
@interface LongriverOneTimeItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic) int64_t purchaseTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LongriverOnlineParamPair;

SWIFT_CLASS("_TtC13LongriverBase27LongriverOnlineConfigResult")
@interface LongriverOnlineConfigResult : NSObject
@property (nonatomic) BOOL isSuccess;
@property (nonatomic, copy) NSArray<LongriverOnlineParamPair *> * _Nonnull data;
- (NSString * _Nonnull)toJson SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase24LongriverOnlineParamPair")
@interface LongriverOnlineParamPair : NSObject
@property (nonatomic, copy) NSString * _Nonnull key;
@property (nonatomic, copy) NSString * _Nonnull value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase28LongriverPaymentParamsResult")
@interface LongriverPaymentParamsResult : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase22LongriverPaymentResult")
@interface LongriverPaymentResult : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) int64_t gameOrderId;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSInteger type;
@property (nonatomic, copy) NSString * _Nonnull transactionId;
@property (nonatomic, copy) NSString * _Nonnull payload;
@property (nonatomic, readonly) BOOL isConsume;
@property (nonatomic, readonly) BOOL isOneTime;
@property (nonatomic, readonly) BOOL isSubscription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase29LongriverSDKAppopenAdDelegate_")
@protocol LongriverSDKAppopenAdDelegate <NSObject>
- (void)onLongriverAppopenAdDidLoad:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverAppopenAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onLongriverAppopenAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverAppopenAdDidHide:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverAppopenAdDidClick:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverAppopenAdDidFailToDisplay:(NSString * _Nonnull)adUnitId code:(NSInteger)code errMsg:(NSString * _Nonnull)errMsg;
- (void)onLongriverAppopenAdDiaTimeout:(NSString * _Nonnull)adUnitId;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase28LongriverSDKBannerAdDelegate_")
@protocol LongriverSDKBannerAdDelegate <NSObject>
- (void)onLongriverBannerAdDidLoad:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverBannerAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onLongriverBannerAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverBannerAdDidHide:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverBannerAdDidExpand:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverBannerAdDidClick:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_CLASS("_TtC13LongriverBase18LongriverSDKConfig")
@interface LongriverSDKConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LongriverStatusCode;
@class LongriverUnConsumeItem;
@class LongriverSubscriptionItem;

SWIFT_PROTOCOL("_TtP13LongriverBase20LongriverSDKDelegate_")
@protocol LongriverSDKDelegate <NSObject>
- (void)onLongriverSdkInitResult:(LongriverStatusCode * _Nonnull)statusCode;
@optional
- (void)onLongriverSdkAttrChanged:(LongriverAttrInfo * _Nullable)attrInfo;
- (void)onLongriverSdkAdvertisingActive;
- (void)onLongriverSdkPullUnConsumeItems:(NSArray<LongriverUnConsumeItem *> * _Nonnull)unConsmeItems;
- (void)onLongriverSdkPullOneTimeItems:(NSArray<LongriverOneTimeItem *> * _Nonnull)oneTimeItems;
- (void)onLongriverSdkPullSubscriptionItems:(NSArray<LongriverSubscriptionItem *> * _Nonnull)subscriptionItems;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase34LongriverSDKInterstitialAdDelegate_")
@protocol LongriverSDKInterstitialAdDelegate <NSObject>
- (void)onLongriverInterstitialAdDidLoad:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverInterstitialAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onLongriverInterstitialAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverInterstitialAdDidHide:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverInterstitialAdDidClick:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase29LongriverSDKLifecycleProtocol_")
@protocol LongriverSDKLifecycleProtocol <NSObject>
@optional
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=9.0);
- (void)scene:(UIScene * _Nonnull)scene openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
- (void)scene:(UIScene * _Nonnull)scene willConnectTo:(UISceneSession * _Nonnull)session options:(UISceneConnectionOptions * _Nonnull)connectionOptions SWIFT_AVAILABILITY(ios,introduced=13.0);
@end


SWIFT_CLASS("_TtC13LongriverBase24LongriverSDKModuleLoader")
@interface LongriverSDKModuleLoader : NSObject
+ (id _Nullable)performWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nullable)arg0 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nullable)performWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nonnull)arg0 arg1:(id _Nonnull)arg1 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nullable)arg0 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nonnull)arg0 arg1:(id _Nonnull)arg1 arg2:(id _Nullable)arg2 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeClassMethodWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nullable)arg0 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeClassMethodWithClassName:(NSString * _Nonnull)className methodName:(NSString * _Nonnull)methodName arg0:(id _Nonnull)arg0 arg1:(id _Nonnull)arg1 arg2:(id _Nullable)arg2 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeInstanceMethodWithObject:(id _Nonnull)object methodName:(NSString * _Nonnull)methodName arg0:(id _Nullable)arg0 SWIFT_WARN_UNUSED_RESULT;
+ (id _Nonnull)invokeInstanceMethodWithObject:(id _Nonnull)object methodName:(NSString * _Nonnull)methodName arg0:(id _Nonnull)arg0 arg1:(id _Nonnull)arg1 arg2:(id _Nullable)arg2 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;

SWIFT_PROTOCOL("_TtP13LongriverBase28LongriverSDKNativeAdDelegate_")
@protocol LongriverSDKNativeAdDelegate <NSObject>
- (void)onLongriverNativeAdDidLoad:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo view:(UIView * _Nullable)view;
- (void)onLongriverNativeAdDidFailToLoad:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onLongriverNativeAdDidClick:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverNativeAdDidRevenue:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase28LongriverSDKRewardAdDelegate_")
@protocol LongriverSDKRewardAdDelegate <NSObject>
- (void)onLongriverRewardAdDidRewardUser:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverRewardAdDidLoad:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverRewardAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onLongriverRewardAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverRewardAdDidHide:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverRewardAdDidClick:(NSString * _Nonnull)adUnitId callback:(LongriverAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onLongriverRewardAdDidFailToDisplay:(NSString * _Nonnull)adUnitId code:(NSInteger)code errMsg:(NSString * _Nonnull)errMsg;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase25LongriverSDKWebAdDelegate_")
@protocol LongriverSDKWebAdDelegate <NSObject>
@optional
- (void)onLongriverWebAdLoaded;
- (void)onLongriverWebAdLoadFailed:(NSString * _Nonnull)errorMsg;
- (void)onLongriverWebAdClose;
- (void)onLongriverWebAdPlayStart;
- (void)onLongriverWebAdPlayFailed:(NSString * _Nonnull)errorMsg;
- (void)onLongriverWebAdReward:(NSString * _Nonnull)msg;
@end


SWIFT_CLASS("_TtC13LongriverBase17LongriverShopItem")
@interface LongriverShopItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) NSInteger type;
@property (nonatomic, copy) NSString * _Nullable appleStoreId;
@property (nonatomic, copy) NSString * _Nullable usdPrice;
@property (nonatomic, copy) NSString * _Nullable formattedPrice;
@property (nonatomic, readonly, copy) NSString * _Nullable itemType;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable price;
@property (nonatomic, readonly) BOOL isConsume;
@property (nonatomic, readonly) BOOL isOneTime;
@property (nonatomic, readonly) BOOL isSubscription;
@end


SWIFT_CLASS("_TtC13LongriverBase22LongriverSignOutResult")
@interface LongriverSignOutResult : NSObject
@property (nonatomic) NSInteger code;
@property (nonatomic, copy) NSString * _Nullable msg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase19LongriverStaticInfo")
@interface LongriverStaticInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class LongriverStatusCodeBuilder;

/// SDK Code
SWIFT_CLASS("_TtC13LongriverBase19LongriverStatusCode")
@interface LongriverStatusCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull Success;)
+ (LongriverStatusCode * _Nonnull)Success SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull Failed;)
+ (LongriverStatusCode * _Nonnull)Failed SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull ErrorPrecondition;)
+ (LongriverStatusCode * _Nonnull)ErrorPrecondition SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull ErrorParameter;)
+ (LongriverStatusCode * _Nonnull)ErrorParameter SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull ErrorInternal;)
+ (LongriverStatusCode * _Nonnull)ErrorInternal SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_CONNECTION_ERROR;)
+ (LongriverStatusCode * _Nonnull)CLIENT_CONNECTION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_CODE_NOT_SUCCESS;)
+ (LongriverStatusCode * _Nonnull)CLIENT_CODE_NOT_SUCCESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_HAS_NOT_LOGIN;)
+ (LongriverStatusCode * _Nonnull)CLIENT_HAS_NOT_LOGIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_NOT_SUPPORT_THIS_LOGINTYPE;)
+ (LongriverStatusCode * _Nonnull)CLIENT_NOT_SUPPORT_THIS_LOGINTYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_GET_LOGIN_PARAMS_FAIL;)
+ (LongriverStatusCode * _Nonnull)CLIENT_GET_LOGIN_PARAMS_FAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_SDK_NOT_INIT;)
+ (LongriverStatusCode * _Nonnull)CLIENT_SDK_NOT_INIT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_AUTO_LOGIN_FAIL;)
+ (LongriverStatusCode * _Nonnull)CLIENT_AUTO_LOGIN_FAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_HAS_LOGIN;)
+ (LongriverStatusCode * _Nonnull)CLIENT_HAS_LOGIN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_APPSTORE_PAY_NOT_CONNECT;)
+ (LongriverStatusCode * _Nonnull)CLIENT_APPSTORE_PAY_NOT_CONNECT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_APPSTORE_PAY_RESPONSE_NOTOK;)
+ (LongriverStatusCode * _Nonnull)CLIENT_APPSTORE_PAY_RESPONSE_NOTOK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_APPSTORE_PAY_SKU_NOT_FOUND;)
+ (LongriverStatusCode * _Nonnull)CLIENT_APPSTORE_PAY_SKU_NOT_FOUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_APPSTORE_PAY_BUY_FAIL;)
+ (LongriverStatusCode * _Nonnull)CLIENT_APPSTORE_PAY_BUY_FAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) LongriverStatusCode * _Nonnull CLIENT_UNKNOW_EXCEPTION;)
+ (LongriverStatusCode * _Nonnull)CLIENT_UNKNOW_EXCEPTION SWIFT_WARN_UNUSED_RESULT;
+ (LongriverStatusCodeBuilder * _Nonnull)Builder SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)getCode SWIFT_WARN_UNUSED_RESULT;
- (void)setCode:(NSInteger)code;
- (NSString * _Nonnull)getMsg SWIFT_WARN_UNUSED_RESULT;
- (void)setMsg:(NSString * _Nonnull)msg;
- (LongriverStatusCode * _Nonnull)withMsg:(NSString * _Nonnull)msg SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)toJson SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13LongriverBase26LongriverStatusCodeBuilder")
@interface LongriverStatusCodeBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13LongriverBase25LongriverSubscriptionItem")
@interface LongriverSubscriptionItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable originalTransactionId;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) int64_t expiredTime;
@property (nonatomic) int64_t leftTime;
@property (nonatomic) BOOL isSubscribed;
@property (nonatomic) BOOL isInFree;
@property (nonatomic) BOOL isInIntroductory;
@property (nonatomic) BOOL isCancel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP13LongriverBase34LongriverThirdUploadLoggerProtocol_")
@protocol LongriverThirdUploadLoggerProtocol <NSObject>
@optional
- (void)logThirdEventWithCustomEvent:(LongriverCustomEvent * _Nonnull)customEvent;
- (void)gameStart;
- (void)registerEvent;
- (void)login;
- (void)level:(NSInteger)level;
- (void)addToCart:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId;
- (void)initCheckout:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId SWIFT_METHOD_FAMILY(none);
- (void)purchase:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId :(NSString * _Nonnull)transacationId;
- (void)incRevenue:(double)price;
- (void)subscription:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)orderId;
- (void)adShow:(NSString * _Nonnull)adType :(NSString * _Nonnull)mediationPlatform :(NSString * _Nonnull)networkName :(NSString * _Nonnull)displayName :(NSString * _Nonnull)adUnitId :(double)revenue;
- (void)log:(NSString * _Nonnull)eventName :(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)uploadAdLoad:(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype;
- (void)uploadAdLoadFail:(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype :(NSInteger)code :(NSString * _Nonnull)messsage;
- (void)uploadAdShow:(NSString * _Nonnull)network_firm_id :(NSString * _Nonnull)adsource_id :(NSString * _Nonnull)network_placement_id :(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype :(double)revenue;
- (void)uploadAdClick:(NSString * _Nonnull)network_firm_id :(NSString * _Nonnull)adsource_id :(NSString * _Nonnull)network_placement_id :(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype;
@end


/// / 定义一个内部结构体，用于存储海滩交易的主要信息
SWIFT_CLASS("_TtC13LongriverBase28LongriverTransactionMainInfo")
@interface LongriverTransactionMainInfo : NSObject
@end


SWIFT_CLASS("_TtC13LongriverBase22LongriverUnConsumeItem")
@interface LongriverUnConsumeItem : NSObject
@property (nonatomic) int64_t gameOrderId;
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase23LongriverUserInfoResult")
@interface LongriverUserInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSArray<LongriverLoginInfo *> * _Nullable loginInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURLSession;
@class NSURLAuthenticationChallenge;
@class NSURLCredential;

SWIFT_CLASS("_TtC13LongriverBase10TCLAppopen")
@interface TCLAppopen : NSObject <NSURLSessionDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session didReceiveChallenge:(NSURLAuthenticationChallenge * _Nonnull)challenge completionHandler:(void (^ _Nonnull)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13LongriverBase11TInfoStatic")
@interface TInfoStatic : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC13LongriverBase20VGYAnalysisParameter")
@interface VGYAnalysisParameter : NSObject
- (void)uploadAdLoad:(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype;
@property (nonatomic, copy) NSArray<id <LongriverThirdUploadLoggerProtocol>> * _Nonnull loggers;
- (void)purchase:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId :(NSString * _Nonnull)transacationId;
- (void)subscription:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)orderId;
- (void)adShow:(NSString * _Nonnull)adType :(NSString * _Nonnull)mediationPlatform :(NSString * _Nonnull)networkName :(NSString * _Nonnull)displayName :(NSString * _Nonnull)adUnitId :(double)revenue;
- (void)incRevenue:(double)revenue;
- (void)logThirdEventWithCustomEvent:(LongriverCustomEvent * _Nonnull)customEvent;
- (void)addToCart:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId;
- (void)gameStart;
- (void)initCheckout:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId SWIFT_METHOD_FAMILY(none);
- (void)level:(NSInteger)level;
- (void)uploadAdClick:(NSString * _Nonnull)network_firm_id :(NSString * _Nonnull)adsource_id :(NSString * _Nonnull)network_placement_id :(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype;
- (void)login;
- (void)registerEvent;
- (void)uploadAdShow:(NSString * _Nonnull)network_firm_id :(NSString * _Nonnull)adsource_id :(NSString * _Nonnull)network_placement_id :(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype :(double)revenue;
+ (VGYAnalysisParameter * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)uploadAdLoadFail:(NSString * _Nonnull)mediationType :(NSString * _Nonnull)unitId :(NSString * _Nonnull)adtype :(NSInteger)code :(NSString * _Nonnull)messsage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
