#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef LONGRIVERSDK_SWIFT_H
#define LONGRIVERSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import LongriverBase;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="LongriverSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSDate;
@class LongriverCustomEvent;
SWIFT_CLASS("_TtC12LongriverSDK7AOHAttr")
@interface AOHAttr : NSObject
- (void)onLogWithJson:(NSString * _Nonnull)jsonString;
- (void)onLogPaySuccess:(NSString * _Nonnull)store transactionId:(NSString * _Nonnull)transactionId productId:(NSString * _Nonnull)productId purchaseDate:(NSDate * _Nonnull)purchaseDate price:(double)price priceString:(NSString * _Nonnull)priceString currency:(NSString * _Nonnull)currency;
+ (AOHAttr * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)onUploadIntoGame:(NSString * _Nullable)server_id server_name:(NSString * _Nullable)server_name role_id:(NSString * _Nullable)role_id role_name:(NSString * _Nullable)role_name;
- (void)onLog:(NSString * _Nonnull)eventName paramMap:(NSDictionary<NSString *, id> * _Nonnull)paramMap;
- (void)onUploadCustomEvent:(LongriverCustomEvent * _Nonnull)customEvent;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12LongriverSDK16EThirdAdverising")
@interface EThirdAdverising : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class LongriverAttrInfo;
SWIFT_CLASS("_TtC12LongriverSDK11EWLifecycle")
@interface EWLifecycle : NSObject
- (NSString * _Nullable)getAttrId SWIFT_WARN_UNUSED_RESULT;
+ (EWLifecycle * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (LongriverAttrInfo * _Nullable)getAttrInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12LongriverSDK12FScreenShare")
@interface FScreenShare : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK5HInfo")
@interface HInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol LongriverSDKInterstitialAdDelegate;
@class LongriverNativeAdBinder;
@protocol LongriverSDKNativeAdDelegate;
@class UIView;
@protocol LongriverSDKRewardAdDelegate;
@protocol LongriverSDKAppopenAdDelegate;
@protocol LongriverSDKBannerAdDelegate;
SWIFT_CLASS("_TtC12LongriverSDK7HLoader")
@interface HLoader : NSObject
- (void)setBannerCustomMode:(BOOL)bannerCustomMode;
- (void)hideBannerAd;
- (void)setLongriverInterstitialAdDelegate:(id <LongriverSDKInterstitialAdDelegate> _Nonnull)delegate;
- (void)showBannerAdWithPosition:(float)x :(float)y;
- (void)showManualNativeAdWithBinder:(LongriverNativeAdBinder * _Nonnull)binder delegate:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)showAppopenAdWithTimeout:(float)timeout;
- (void)showRewardedAd:(NSString * _Nullable)placementId;
+ (HLoader * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAdBottomOfSafe;
- (CGSize)getBannerSize SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)createBanner SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isRewardedAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAdTop;
- (NSString * _Nonnull)getLoadingStatusSummary SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAdTopOfSafe;
- (void)showMediumNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)showInterstitialAd:(NSString * _Nullable)placementId;
- (void)showBannerAd;
- (void)setLongriverRewardAdDelegate:(id <LongriverSDKRewardAdDelegate> _Nonnull)delegate;
- (void)setLongriverAppopenAdDelegate:(id <LongriverSDKAppopenAdDelegate> _Nonnull)delegate;
- (void)destroyBanner;
- (void)showSmallNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)destroyNativeAdView:(UIView * _Nonnull)view;
- (void)setLongriverBannerAdDelegate:(id <LongriverSDKBannerAdDelegate> _Nonnull)delegate;
- (void)showBannerAdBottom;
- (BOOL)isBannerAdReady SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isInterstitialAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showCollapsibleBannerAd:(NSString * _Nullable)position;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol LongriverSDKDelegate;
SWIFT_CLASS("_TtC12LongriverSDK12LongriverSDK")
@interface LongriverSDK : NSObject
+ (LongriverSDK * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasInit SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getStaticInfoOfString SWIFT_WARN_UNUSED_RESULT;
- (void)enableSimpleMode;
- (NSString * _Nonnull)getAdMediationType SWIFT_WARN_UNUSED_RESULT;
- (void)sdkInit:(id <LongriverSDKDelegate> _Nonnull)delegate;
- (void)sdkInitWithDict:(NSDictionary<NSString *, id> * _Nonnull)configDict delegaate:(id <LongriverSDKDelegate> _Nonnull)delegaate;
- (void)sdkInitWithJson:(NSString * _Nonnull)configJson delegate:(id <LongriverSDKDelegate> _Nonnull)delegate;
- (void)onLongriverUMPInitDelegate:(id _Nullable)any;
- (void)onLongriverUMPPopDelegate:(id _Nullable)any;
- (void)onLongriverAdvertisingInitDelegate:(id _Nullable)any;
- (void)onLongriverAdvertisingAppopenAdDelegate:(id _Nullable)any;
- (void)onLongriverAdvertisingRewardedAdDelegate:(id _Nullable)any;
- (void)onLongriverAdvertisingInterstitialAdDelegate:(id _Nullable)any;
- (void)onLongriverAdvertisingBannerAdDelegate:(id _Nullable)any;
- (void)onLongriverAdmobAdvertisingBannerAdDelegate:(id _Nullable)any;
- (void)onLongriverBuglyMonitorInitDelegate:(id _Nullable)any;
- (void)onLongriverAttributeInitDelegate:(id _Nullable)any;
- (void)onLongriverAttributeChangedDelegate:(id _Nullable)any;
- (void)onLongriverAnalysisInitDelegate:(id _Nullable)any;
- (void)onLongriverLogUoloadInitDelegate:(id _Nullable)any;
- (void)onLongriverLoginInitDelegate:(id _Nullable)any;
- (void)onLongriverPurchaseInitDelegate:(id _Nullable)any;
- (void)onLongriverShareInitDelegate:(id _Nullable)any;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (NSString * _Nullable)getAttrId SWIFT_WARN_UNUSED_RESULT;
- (LongriverAttrInfo * _Nullable)getAttrInfo SWIFT_WARN_UNUSED_RESULT;
@end

@class UIImage;
@class LongriverStatusCode;
@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (NSArray<NSString *> * _Nonnull)getShareTypes SWIFT_WARN_UNUSED_RESULT;
- (void)sharePhoto:(NSString * _Nonnull)shareType image:(UIImage * _Nonnull)image success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)shareLink:(NSString * _Nonnull)shareType url:(NSString * _Nonnull)url success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
@end

@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (void)onMessageing:(NSString * _Nonnull)token;
- (void)disableRemoteNotifications;
- (void)enableRemoteNotifications;
@end

@class UIScene;
@class UISceneSession;
@class UISceneConnectionOptions;
@class UIApplication;
@class NSURL;
@class UIOpenURLContext;
@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (void)scene:(UIScene * _Nonnull)scene willConnectTo:(UISceneSession * _Nonnull)session options:(UISceneConnectionOptions * _Nonnull)connectionOptions SWIFT_AVAILABILITY(ios,introduced=13.0);
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
- (void)scene:(UIScene * _Nonnull)scene openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
@end

@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (void)onLogWithJson:(NSString * _Nonnull)jsonString;
- (void)onLogPaySuccess:(NSString * _Nonnull)store transactionId:(NSString * _Nonnull)transactionId productId:(NSString * _Nonnull)productId purchaseDate:(NSDate * _Nonnull)purchaseDate price:(double)price priceString:(NSString * _Nonnull)priceString currency:(NSString * _Nonnull)currency;
- (void)onUploadCustomEvent:(LongriverCustomEvent * _Nonnull)customEvent;
- (void)onLog:(NSString * _Nonnull)eventName paramMap:(NSDictionary<NSString *, id> * _Nonnull)paramMap;
@end

@class LongriverAutoLoginResult;
@class LongriverCheckLoginResult;
@class LongriverLoginResult;
@class LongriverUserInfoResult;
@class LongriverSignOutResult;
@class LongriverGetBindTransferCodeResult;
@class LongriverGenerateTransferCodeResult;
@class LongriverBindTransferCodeResult;
@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
@property (nonatomic, readonly, copy) NSString * _Nullable gameId;
@property (nonatomic, readonly) BOOL isLogin;
@property (nonatomic, readonly) int64_t gameAccountId;
- (NSArray<NSString *> * _Nonnull)getLoginTypes SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionToken;
- (void)uploadRoleLogin:(NSString * _Nonnull)serverId serverName:(NSString * _Nonnull)serverName roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nonnull)roleName;
- (void)autoLoginAsync:(BOOL)needGameCenter success:(void (^ _Nonnull)(LongriverAutoLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)checkLoginAsync:(void (^ _Nonnull)(LongriverCheckLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)loginWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)unbindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)getUserInfoAsync:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)logout;
- (void)signOut:(void (^ _Nonnull)(LongriverSignOutResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)getBindTransferCode:(void (^ _Nonnull)(LongriverGetBindTransferCodeResult * _Nullable))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)generateTransferCode:(void (^ _Nonnull)(LongriverGenerateTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindTransferCode:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(LongriverBindTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindTransferCodeAndReLogin:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(LongriverLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
@end

@class UIColor;
@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (void)showMediumNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)hideBannerAd;
- (void)showManualNativeAdWithBinder:(LongriverNativeAdBinder * _Nonnull)binder delegate:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)showRewardedAd:(NSString * _Nullable)placementId;
- (BOOL)isInterstitialAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showInterstitialAd:(NSString * _Nullable)placementId;
- (CGSize)getBannerSize SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAd;
- (BOOL)isBannerAdReady SWIFT_WARN_UNUSED_RESULT;
- (void)showSmallNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (UIView * _Nullable)createBanner SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverAppopenAdDelegate:(id <LongriverSDKAppopenAdDelegate> _Nonnull)delegate;
- (NSString * _Nonnull)getLoadingStatusSummary SWIFT_WARN_UNUSED_RESULT;
- (void)destroyBanner;
- (void)destroyNativeAdView:(UIView * _Nonnull)view;
- (void)showBannerAdBottomOfSafe;
- (void)showAppopenAdWithTimeout:(float)timeout;
- (void)setLongriverRewardAdDelegate:(id <LongriverSDKRewardAdDelegate> _Nonnull)delegate;
- (void)setLongriverInterstitialAdDelegate:(id <LongriverSDKInterstitialAdDelegate> _Nonnull)delegate;
- (void)showBannerAdTopOfSafe;
- (BOOL)isRewardedAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverBannerAdDelegate:(id <LongriverSDKBannerAdDelegate> _Nonnull)delegate;
- (void)showBannerAdTop;
- (void)setBannerCustomMode:(BOOL)bannerCustomMode;
- (void)showBannerAdWithPosition:(float)x :(float)y;
- (void)showBannerAdBottom;
- (void)setBannerBackgroundColor:(UIColor * _Nonnull)color;
@end

@protocol LongriverSDKWebAdDelegate;
@interface LongriverSDK (SWIFT_EXTENSION(LongriverSDK))
- (void)setLongriverWebAdDelegate:(id <LongriverSDKWebAdDelegate> _Nonnull)delegate;
- (BOOL)isWebAdReady SWIFT_WARN_UNUSED_RESULT;
- (void)showUrl;
@end

SWIFT_CLASS("_TtC12LongriverSDK17LongriverSDKLogin")
@interface LongriverSDKLogin : NSObject
/// 访问 EWLifecycle 单例
///
/// returns:
/// 返回 EWLifecycle 单例
+ (LongriverSDKLogin * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable gameId;
@property (nonatomic, readonly) BOOL isLogin;
@property (nonatomic, readonly) int64_t gameAccountId;
- (NSArray<NSString *> * _Nonnull)getLoginTypes SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionToken;
- (void)uploadRoleLogin:(NSString * _Nonnull)serverId serverName:(NSString * _Nonnull)serverName roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nonnull)roleName;
- (void)autoLoginAsync:(BOOL)needGameCenter success:(void (^ _Nonnull)(LongriverAutoLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)checkLoginAsync:(void (^ _Nonnull)(LongriverCheckLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)loginWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)unbindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)getUserInfoAsync:(void (^ _Nonnull)(LongriverUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)logout;
- (void)signOut:(void (^ _Nonnull)(LongriverSignOutResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)getBindTransferCode:(void (^ _Nonnull)(LongriverGetBindTransferCodeResult * _Nullable))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)generateTransferCode:(void (^ _Nonnull)(LongriverGenerateTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindTransferCode:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(LongriverBindTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)bindTransferCodeAndReLogin:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(LongriverLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (NSInteger)tryLaunchOrOpenAppStore:(NSString * _Nonnull)appURLScheme :(NSString * _Nonnull)appStoreURL :(NSDictionary<NSString *, id> * _Nonnull)dataDict SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverAppJumpDelegate:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class LongriverShopItem;
@class LongriverPaymentResult;
@class LongriverOneTimeItem;
@class LongriverSubscriptionItem;
SWIFT_CLASS("_TtC12LongriverSDK15LongriverSDKPay")
@interface LongriverSDKPay : NSObject
/// 访问 EWLifecycle 单例
///
/// returns:
/// 返回 EWLifecycle 单例
+ (LongriverSDKPay * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverTransactionStatusDelegate:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))delegate;
- (NSArray<LongriverShopItem *> * _Nullable)getShopItems SWIFT_WARN_UNUSED_RESULT;
- (void)getShopItemAsyncWithSuccess:(void (^ _Nonnull)(NSArray<LongriverShopItem *> * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)startPayment:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId success:(void (^ _Nonnull)(LongriverPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)startPaymentWithEnvId:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId envId:(NSString * _Nonnull)envId success:(void (^ _Nonnull)(LongriverPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)startPaymentWithExtraInfo:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId extraInfo:(NSDictionary<NSString *, NSString *> * _Nonnull)extraInfo success:(void (^ _Nonnull)(LongriverPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)startPaymentWithEnvIdAndExtraInfo:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId envId:(NSString * _Nullable)envId extraInfo:(NSDictionary<NSString *, NSString *> * _Nullable)extraInfo success:(void (^ _Nonnull)(LongriverPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)onConsumeItem:(int64_t)gameOrderId success:(void (^ _Nonnull)(int64_t))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)queryOneTimeItemAsync:(void (^ _Nonnull)(NSArray<LongriverOneTimeItem *> * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)querySubsrciptionAsync:(void (^ _Nonnull)(NSArray<LongriverSubscriptionItem *> * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (void)onRestoreApplePurchases;
- (void)onRestoreApplePurchasesWithCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum LongriverUMPDebugGeography : NSInteger;
SWIFT_CLASS("_TtC12LongriverSDK15LongriverSDKUMP")
@interface LongriverSDKUMP : NSObject
- (void)showPrivacyOptionsForm:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))block;
- (void)setUmpWithIp:(BOOL)enable;
- (BOOL)isPrivacyOptionsRequired SWIFT_WARN_UNUSED_RESULT;
- (void)addTestDeviceHashedId:(NSString * _Nonnull)deviceHashedId;
+ (LongriverSDKUMP * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getUMPParameters SWIFT_WARN_UNUSED_RESULT;
- (void)setDebugGeography:(enum LongriverUMPDebugGeography)debugGeoraphy;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, LongriverUMPDebugGeography, closed) {
  LongriverUMPDebugGeographyDisabled = 0,
  LongriverUMPDebugGeographyEEA = 1,
  LongriverUMPDebugGeographyRegulatedUSState = 2,
};

SWIFT_CLASS("_TtC12LongriverSDK18MOCAnalyticsManual")
@interface MOCAnalyticsManual : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK14NRCollectLocal")
@interface NRCollectLocal : NSObject
- (NSArray<NSString *> * _Nonnull)getShareTypes SWIFT_WARN_UNUSED_RESULT;
- (void)sharePhoto:(NSString * _Nonnull)shareType image:(UIImage * _Nonnull)image success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
+ (NRCollectLocal * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)shareLink:(NSString * _Nonnull)shareType url:(NSString * _Nonnull)url success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(LongriverStatusCode * _Nonnull))failed;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12LongriverSDK8OZModule")
@interface OZModule : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK8PCollect")
@interface PCollect : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK13QAttributtion")
@interface QAttributtion : NSObject <LongriverThirdUploadLoggerProtocol>
- (NSString * _Nullable)getEventName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (void)uploadEvent:(NSString * _Nonnull)eventName :(NSDictionary<NSString *, id> * _Nonnull)params;
- (void)addToCart:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId;
- (void)login;
- (void)disableRemoteNotifications;
- (void)incRevenue:(double)price;
- (void)fetchRemoteConfig;
- (void)purchase:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId :(NSString * _Nonnull)transacationId;
- (void)subscription:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)orderId;
- (id _Nonnull)fetchRemoteConfigValueForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)enableRemoteNotifications;
- (void)registerEvent;
- (void)level:(NSInteger)level;
- (NSString * _Nullable)getParameterName:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (void)adShow:(NSString * _Nonnull)adType :(NSString * _Nonnull)mediationPlatform :(NSString * _Nonnull)networkName :(NSString * _Nonnull)displayName :(NSString * _Nonnull)adUnitId :(double)revenue;
- (void)initCheckout:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId SWIFT_METHOD_FAMILY(none);
- (id _Nonnull)setRemoteConfigDefaults:(NSDictionary<NSString *, NSObject *> * _Nonnull)defaults SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK15TEVTestRewarded")
@interface TEVTestRewarded : NSObject
- (void)showInterstitialAd:(NSString * _Nullable)placementId;
- (void)showBannerAdTop;
- (void)destroyNativeAdView:(UIView * _Nonnull)view;
- (void)hideBannerAd;
- (void)showRewardedAd:(NSString * _Nullable)placementId;
- (UIView * _Nullable)createBanner SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAdWithPosition:(float)x :(float)y;
- (BOOL)isRewardedAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAdBottomOfSafe;
- (BOOL)isInterstitialAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showCollapsibleBannerAd:(NSString * _Nullable)position;
- (void)setLongriverRewardAdDelegate:(id <LongriverSDKRewardAdDelegate> _Nonnull)delegate;
- (void)showBannerAdTopOfSafe;
- (void)showBannerAd;
- (NSString * _Nonnull)getLoadingStatusSummary SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverBannerAdDelegate:(id <LongriverSDKBannerAdDelegate> _Nonnull)delegate;
- (void)showMediumNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)showBannerAdBottom;
- (void)setLongriverInterstitialAdDelegate:(id <LongriverSDKInterstitialAdDelegate> _Nonnull)delegate;
- (void)showManualNativeAdWithBinder:(LongriverNativeAdBinder * _Nonnull)binder delegate:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (void)destroyBanner;
- (void)showAppopenAdWithTimeout:(float)timeout;
- (void)showSmallNativeAd:(id <LongriverSDKNativeAdDelegate> _Nullable)delegate;
- (BOOL)isBannerAdReady SWIFT_WARN_UNUSED_RESULT;
+ (TEVTestRewarded * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setLongriverAppopenAdDelegate:(id <LongriverSDKAppopenAdDelegate> _Nonnull)delegate;
- (CGSize)getBannerSize SWIFT_WARN_UNUSED_RESULT;
- (void)setBannerCustomMode:(BOOL)bannerCustomMode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12LongriverSDK17TIKCustomAnalysis")
@interface TIKCustomAnalysis : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK7VBridge")
@interface VBridge : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC12LongriverSDK15WJLInfoRewarded")
@interface WJLInfoRewarded : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK10XKFPrivacy")
@interface XKFPrivacy : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC12LongriverSDK17YIYFacebooService")
@interface YIYFacebooService : NSObject
- (NSString * _Nullable)getRemoteConfigForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)onMessageing:(NSString * _Nonnull)token;
- (void)disableRemoteNotifications;
+ (YIYFacebooService * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)setRemoteConfigDefaults:(NSDictionary<NSString *, NSObject *> * _Nonnull)defaults;
- (void)enableRemoteNotifications;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
